
#version 460

layout (local_size_x = 1, local_size_y = 1024, local_size_z = 1) in;
layout (rgba32f) uniform image2D fftImgRe;
layout (rgba32f) uniform image2D fftImgIm;

uniform sampler2D fftTexRe;
uniform sampler2D fftTexIm;

uniform sampler2D kernelTexRe;
uniform sampler2D kernelTexIm;

#include "lib/utility.glsl"
#include "lib/fft.glsl"

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);

    ColumnPreload(iPos, fftTexRe, fftTexIm);

    for (int i = 1; i <= 10; i++) {
        barrier();
        ComplexVec3 result = FFT(iPos.y, 1024, i, false);
        barrier();
        sharedBuffer[iPos.y] = result;
    }

    vec3 kernelRe = texelFetch(kernelTexRe, iPos, 0).rgb;
    vec3 kernelIm = texelFetch(kernelTexIm, iPos, 0).rgb;

    vec3 a = sharedBuffer[iPos.y].re;
    vec3 b = sharedBuffer[iPos.y].im;
    vec3 c = kernelRe;
    vec3 d = kernelIm;

    // Complex multiplication
    vec3 re = a * c - b * d;
    vec3 im = a * d + b * c;

    sharedBuffer[iPos.y].re = re;
    sharedBuffer[iPos.y].im = im;

    imageStore(fftImgRe, iPos, vec4(sharedBuffer[iPos.y].re, 0.0));
    imageStore(fftImgIm, iPos, vec4(sharedBuffer[iPos.y].im, 0.0));
}