
#version 460

layout (local_size_x = 1, local_size_y = 1024, local_size_z = 1) in;
layout (rgba32f) uniform image2D fftTexRe_b;
layout (rgba32f) uniform image2D fftTexIm_b;

uniform sampler2D fftTexRe_a;
uniform sampler2D fftTexIm_a;

#include "lib/utility.glsl"
#include "lib/fft.glsl"

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);

    ColumnPreload(iPos, fftTexRe_a, fftTexIm_a);

    for (int i = 1; i <= 10; i++) {
        barrier();
        ComplexVec3 result = FFT(iPos.y, 1024, i, true);
        barrier();
        sharedBuffer[iPos.y] = result;
    }

    imageStore(fftTexRe_b, iPos, vec4(sharedBuffer[iPos.y].re, 0.0));
    imageStore(fftTexIm_b, iPos, vec4(sharedBuffer[iPos.y].im, 0.0));
}