#version 460 

layout (local_size_x = 3, local_size_y = 3, local_size_z = 3) in;
layout (r32f) uniform image3D outputTex;

uniform sampler3D inputTex;

void main() {
    ivec3 iPos = ivec3(gl_GlobalInvocationID);

    vec3 outImageSize = imageSize(outputTex);

    if (any(greaterThanEqual(iPos, outImageSize))) return;

    
    float value = 0.0;
    
    if (iPos.z < outImageSize.z)
        value = texelFetch()
    else 
        value = 

    imageStore(outputTex, iPos, vec4(value));
}