#version 460 

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout (r32f) uniform image3D outputTex;

uniform sampler2D videoTex;

uniform uint accumulationIndex;

uniform float currentFrame;
uniform float contrast;

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID);

    vec3 rgb = texelFetch(videoTex, iPos.xy, 0).rgb;

    float luminance = 0.2126 * rgb.r + 0.7152 * rgb.g + 0.0722 * rgb.b;
    luminance = (luminance - 0.5) * contrast + 0.5;
    luminance = clamp(luminance, 0.0, 1.0);
    imageStore(outputTex, ivec3(iPos.x, iPos.y, 0), vec4(pow(luminance, 2.2)));
}