
#version 460

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f) uniform image2D waveImgRe;
layout (rgba32f) uniform image2D waveImgIm;

uniform float currentFrame;
uniform float waveHeightMult;
uniform float windSpeed;
uniform float fieldSize;

#include "lib/utility.glsl"
#include "lib/fft.glsl"
#include "lib/rand.glsl"
#include "lib/tessendorf.glsl"

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);
    InitRand(uint(gl_GlobalInvocationID.x + 1024 * gl_GlobalInvocationID.y));

    vec2 k = GetWaveFieldCoord(ShiftCoordinates(iPos));
    Complex waveAmplitudes = ComputeWaveAmplitudes(k, currentFrame * 0.5);

    ivec2 shiftedCoord = ShiftCoordinates(iPos);

    RowPreload(iPos, waveAmplitudes);
    barrier();

    for (int i = 1; i <= 10; i++) {
        barrier();
        ComplexVec3 result = FFT(iPos.x, 1024, i, true);
        barrier();
        sharedBuffer[iPos.x] = result;
    }

    imageStore(waveImgRe, iPos, vec4(sharedBuffer[iPos.x].re, 0.0));
    imageStore(waveImgIm, iPos, vec4(sharedBuffer[iPos.x].im, 0.0));
}