
#version 460

layout (local_size_x = 1, local_size_y = 1024, local_size_z = 1) in;
layout (rgba32f) uniform image2D waveImgRe;
layout (rgba32f) uniform image2D waveImgIm;

uniform sampler2D waveTexRe;
uniform sampler2D waveTexIm;

#include "lib/utility.glsl"
#include "lib/fft.glsl"
#include "lib/rand.glsl"

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);

    ColumnPreload(iPos, waveTexRe, waveTexIm);

    for (int i = 1; i <= 10; i++) {
        barrier();
        ComplexVec3 result = FFT(iPos.y, 1024, i, true);
        barrier();
        sharedBuffer[iPos.y] = result;
    }

    imageStore(waveImgRe, iPos, vec4(sharedBuffer[iPos.y].re, 0.0));
    imageStore(waveImgIm, iPos, vec4(sharedBuffer[iPos.y].im, 0.0));
}