#version 460 

layout (local_size_x = 3, local_size_y = 3, local_size_z = 3) in;
layout (r32f) uniform image3D outputTex;

uniform sampler3D inputTex;

void main() {
    ivec3 iPos = ivec3(gl_GlobalInvocationID);

    // TODO: Move the LeakyReLU alpha to a uniform, so it can be controlled through JSON
    float value = texelFetch(inputTex, iPos, 0).r;
    value = value > 0.0 ? value : value * 0.1;

    imageStore(outputTex, iPos, vec4(value));
}