#version 460

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (rgba8) uniform image2D imageOut;

uniform sampler2D fftTexRe;

uniform sampler2D imageLinear;
uniform sampler2D normalTex;
uniform sampler3D colorLookup;
uniform sampler3D colorLookupPost;

uniform sampler2D kernelTexRe;

#include "lib/utility.glsl"

void main() {
    ivec2 iCoord = ivec2(gl_GlobalInvocationID.xy);
    vec2 nCoord = (iCoord + 0.5) / (gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

    vec3 stimulus = texture(fftTexRe, nCoord).rgb / pow(1024, 2.0) * 0.05;
         stimulus += texture(imageLinear, nCoord).rgb * 2.0;
    vec3 coord = stimulus / (stimulus + 1.0);
         coord.y = 1.0 - coord.y;

    vec3 color = texture(colorLookup, coord).rgb;
         // color = texture(colorLookupPost, color).rgb;
         // color = texture(kernelTexRe, nCoord).rgb * 10;
         // color = stimulus;

     // color = texture(normalTex, nCoord).rgb;

    imageStore(imageOut, iCoord, vec4(color, 1.0));
}