#version 460

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout (rgba16f) uniform image2D imageLinear;

uniform mat4 cameraProjectionMatrix;
uniform mat4 cameraProjectionMatrixInverse;
uniform mat4 cameraViewMatrix;
uniform mat4 cameraViewMatrixInverse;

uniform vec3 cameraPosition;

uniform float currentFrame;

uniform sampler3D voxelTex;

uniform sampler2D fujiTex;

#include "lib/utility.glsl"
#include "lib/intersections.glsl"

vec3 CalculateCameraRayDir(const vec2 nCoord, const mat4 projectionMatrixInverse, const mat4 viewMatrixInverse) {
    vec3 rayDir = vec3(nCoord, 1.0) * 2.0 - 1.0;
    vec4 tmp = projectionMatrixInverse * vec4(rayDir, 1.0);
         rayDir = tmp.xyz / tmp.w;
         rayDir = mat3(viewMatrixInverse) * rayDir;
         rayDir = normalize(rayDir);
    
    return rayDir;
}

vec2 Rand(vec2 n) { 
	return vec2(
        clamp(fract(sin(dot(n + fract(currentFrame), vec2(12.9898, 4.1414))) * 43758.5453), 0.0, 1.0),
        clamp(fract(cos(dot(n - fract(currentFrame), vec2(12.9898, 4.1414))) * 43758.5453), 0.0, 1.0)
    );
}

vec3 GenerateUnitVector(vec2 xy) {
    xy.x *= TAU; xy.y = xy.y * 2.0 - 1.0;
    return vec3(sincos(xy.x) * sqrt(1.0 - xy.y * xy.y), xy.y);
}

vec3 GenerateConeVector(vec3 vector, float angle, vec2 xy) {
    vec3 v = GenerateUnitVector(xy);
    float VoD = dot(v, vector);

    float cosAngle = cos(angle);
    float newCosTheta = VoD * (1.0 - cosAngle) + cosAngle;

    return sqrt(1.0 - newCosTheta * newCosTheta) * inversesqrt(1.0 - VoD * VoD) * (v - vector * VoD) + newCosTheta * vector;
}

vec3 RenderDirectDiffuse(vec3 worldPos, vec3 normal, Material material, const vec3 lightPositions[3], const vec3 lightColors[3], vec2 rand) {
    if (material.isEmissive) return material.albedo;

    vec3 radiance = vec3(0.0);

    for (int i = 0; i < 3; i++) {
        vec3 lightDir = normalize(lightPositions[i] - worldPos);
             lightDir = GenerateConeVector(lightDir, 0.05, rand);
        float distToLight = length(lightPositions[i] - worldPos);

        HitData hitData = emptyHitData;
        RayTraceScene(hitData, worldPos + normal * 0.001, lightDir, lightPositions, lightColors, true);

        float shadow = 1.0;
        if (hitData.rayHit && abs(hitData.t) < abs(distToLight)) {
            shadow = 0.2;
        }

        float NdotL = max(dot(lightDir, normal), 0.0);
        radiance += shadow * material.albedo * lightColors[i] * NdotL / (distToLight * distToLight);
    }

    return radiance;
}


void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);
    vec2 nCoord = (iPos + 0.5) / (gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

    vec3 rayDirection = CalculateCameraRayDir(nCoord, cameraProjectionMatrixInverse, cameraViewMatrixInverse);
    vec3 rayOrigin = cameraPosition;

    HitData hitData = emptyHitData;

    vec3 lightPositions[3] = vec3[3](
        vec3(27.0, 57.5 * sin(currentFrame * 0) + 57.5, 90.0),
        vec3(-13.0, 57.5 * sin(currentFrame * 0 + 2 * PI / 3.0) + 57.5, 30.0),
        vec3(67.0, 57.5 * 2.0, 30.0)
    );

    vec3 lightColors[3] = vec3[3](
        vec3(1.0, 0.6, 0.4),
        vec3(0.4, 0.7, 1.0),
        vec3(1.0, 1.0, 1.0)
    );

    RayTraceScene(hitData, rayOrigin, rayDirection, lightPositions, lightColors, false);

    if (!hitData.rayHit) {
        imageStore(imageLinear, iPos, vec4(0.0));
        return;
    }

    vec2 rand = Rand(nCoord);
    vec3 color = RenderDirectDiffuse(hitData.hitPos, hitData.hitNormal, hitData.material, lightPositions, lightColors, rand);
    imageStore(imageLinear, iPos, vec4(color, 0.0));
}