
#version 460

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f) uniform image2D fftImgRe;
layout (rgba32f) uniform image2D fftImgIm;

uniform sampler2D fftTexRe;
uniform sampler2D fftTexIm;

#include "lib/utility.glsl"
#include "lib/fft.glsl"

void main() {
    ivec2 iPos = ivec2(gl_GlobalInvocationID.xy);

    RowPreload(iPos, fftTexRe, fftTexIm);

    for (int i = 1; i <= 10; i++) {
        barrier();
        ComplexVec3 result = FFT(iPos.x, 1024, i, true);
        barrier();
        sharedBuffer[iPos.x] = result;
    }

    imageStore(fftImgRe, iPos, vec4(sharedBuffer[iPos.x].re, 0.0));
    imageStore(fftImgIm, iPos, vec4(sharedBuffer[iPos.x].im, 0.0));
}