#version 460 core 

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (rgba16f, binding = 5) uniform writeonly image2D imageOut;

uniform sampler2D sceneAlbedo;
uniform sampler3D colorLookup;
uniform sampler2D heightMap;

void main() {
    vec2 iPos = gl_GlobalInvocationID.xy;
    vec2 texcoord = iPos / gl_NumWorkGroups.xy;

    vec4 color = texture(heightMap, texcoord);
    imageStore(imageOut, ivec2(iPos), color);
}