name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libglfw3-dev libglfw3 mingw-w64

    - name: Build (Linux)
      run: | 
        cd ${{github.workspace}}
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
      
    - name: Build (Windows)
      run: |
        cd ${{github.workspace}}
        mkdir buildwin && cd buildwin
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=mingw-w64-x86_64.cmake ..
        make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Upload build artifacts (Linux)
      uses: actions/upload-artifact@v3
      with:
          name: upload-build-linux
          path: build/bin
          
    - name: Upload build artifacts (Windows)
      uses: actions/upload-artifact@v3
      with:
          name: upload-build-windows
          path: buildwin/bin
